name = "Arc Unoffical Minecraft 26"
author = "ImDefiant"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e880103555acb7c31c57abc4d0caf4e236795e0f169f556e52e5bed675a4083"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
