name = "Arc Unoffical Minecraft 26"
author = "ImDefiant"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "452841c15396f4daa74278e9413d1f38ccb3ad36f9d339ecdc48e25b61b4d70b"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
